from . import res_partner
from . import res_company
from . import cloth_brand
from . import cloth_collection
from . import cloth_size
from . import cloth_markup
from . import cloth_receipt
from . import cloth_order
from . import cloth_product
from . import res_config_settings
